export const modalType = {
	LEAVE_REASON: "LEAVE_REASON",
	SELECT_CHARACTER: "SELECT_CHARACTER",
	SELECT_GENDER: "SELECT_GENDER",
	CHANGE_NICKNAME: "CHANGE_NICKNAME",
	SELECT_AGE: "SELECT_AGE",
	SELECT_IDENTITY: "SELECT_IDENTITY",
	LOGOUT: "LOGOUT",
	SORT: "SORT",
	DELETE_HISTORY: (id: number) => `DELETE_HISTORY_${id}`,
};
